const LOGIN_ROUTE = "LOGIN_ROUTE";
const HOME_ROUTE = "HOME_ROUTE";
const TASKS_ROUTE = "Задачи";
const TASKS_DETAIL_ROUTE = "TASKS_DETAIL_ROUTE";
const PROFILE_ROUTE = "PROFILE_ROUTE";
const ORDERS_ROUTE = "Заказы";
const SETTINGS_ROUTE = "Настройки";
// const ORDER_DETAIL_ROUTE = '/ORDER_DETAIL';
// const MOYSKLAD_ROUTE = '/MOYSKLAD';
// const MOVES_DETAIL_ROUTE = '/MOVES_DETAIL';
// const CONTROL_PANEL_ROUTE = '/CONTROL_PANEL';
// const INITIAL_SETTINGS_ROUTE = '/INITIAL_SETTINGS';

export {
  LOGIN_ROUTE,
  HOME_ROUTE,
  TASKS_ROUTE,
  TASKS_DETAIL_ROUTE,
  PROFILE_ROUTE,
  ORDERS_ROUTE,
  SETTINGS_ROUTE,
  // ORDER_DETAIL_ROUTE,
  // MOYSKLAD_ROUTE,
  // MOVES_DETAIL_ROUTE,
  // CONTROL_PANEL_ROUTE,
  // INITIAL_SETTINGS_ROUTE,
};
